import styles from "./Faq.module.css";

const questions = [
  ["Welche TORK-Handtücher passen in welchen Wagen?", "Im Wagen S werden Tork Matic Advanced Handtuchrollen H1 verwendet. Für die Wagen M und L passen Tork Express Multifold Handtücher Universal H2. Bitte achten Sie beim Nachkauf auf das passende System. Alle drei Wagen erhalten dieselbe Erstausstattung: Toilettenpapier, Seife und Papierhandtücher."],
  ["Welcher Wagen passt zu meiner Veranstaltung?", "Modell S ist für bis zu 200 Personen, M für bis zu 400 und L für bis zu 600 Personen vorgesehen. Im Anfrageformular wählen Sie das gewünschte Modell zuerst aus. Wenn Sie noch unsicher sind, wählen Sie „Noch unsicher“ – wir beraten Sie persönlich."],
  ["In welche Orte liefern Sie?", "Unser reguläres Einsatzgebiet reicht ungefähr 125 km um den Wagenstandort Niederdreisbach. Dazu gehören beispielsweise Daaden, Herdorf, Neunkirchen, Niederfischbach, Dillenburg, Haiger, Siegen, Netphen, Rennerod und Betzdorf. Weitere Strecken prüfen wir auf Anfrage."],
  ["Woran erkenne ich einen GEKA- oder Gardena-Anschluss?", "Eine GEKA-Kupplung erkennen Sie an zwei gegenüberliegenden Klauen und einem Dichtungsring. Bei Gardena hat das männliche Steckteil einen hervorstehenden Anschlusszapfen; das weibliche Schlauchstück besitzt eine Aufnahmeöffnung und eine Entriegelungshülse. Beispielabbildungen finden Sie weiter oben beim Wasseranschluss. Die genaue Ausführung stimmen wir vorab mit Ihnen ab."],
  ["Welche Anschlüsse und welchen Untergrund brauchen wir?", "Bitte stellen Sie 230 V Strom, einen Wasseranschluss mit GEKA- oder Gardena-Kupplung und einen geeigneten, zulässigen Abwasseranschluss bereit. Für den Abwasseranschluss empfehlen wir höchstens fünf Meter Abstand zum Wagen. Aufstellort und Anschluss müssen vor der Lieferung feststehen und nutzbar sein. Die Aufstellfläche muss fest und eben sein. Wir bringen zehn Meter Frischwasserschlauch, Abwasserrohre und maßgefertigte Holzabdeckungen für Kanaldeckel mit."],
  ["Brauche ich eine Genehmigung für den Abwasseranschluss?", "Auf öffentlichen Flächen müssen Sie die erforderlichen Genehmigungen selbst rechtzeitig einholen. Diese müssen uns vor der Lieferung schriftlich vorliegen. Wir übernehmen weder die Beantragung noch die Klärung vor Ort. Auf privatem Grund entfällt die Genehmigung zur Nutzung einer öffentlichen Fläche; die Zustimmung des Eigentümers und die örtlichen Vorgaben für den Abwasseranschluss bleiben zu beachten. Auch dort müssen Sie einen geeigneten und zulässigen Anschluss vorab sicherstellen. Reine Regenwasserabläufe sind nicht für Toilettenabwasser geeignet."],
  ["Was ist als Erstausstattung enthalten?", "S, M und L erhalten dieselbe Erstausstattung: Toilettenpapier, Seife und Papierhandtücher. Lediglich das Handtuchsystem unterscheidet sich: TORK H1 im Wagen S, TORK H2 in M und L. Wenn die Erstausstattung aufgebraucht ist, können Sie Toilettenpapier, Seife und Papierhandtücher bei uns nachkaufen."],
  ["Wie werden Lieferung und Abholung berechnet?", "Wir addieren nur die Strecken mit angehängtem Toilettenwagen: die Lieferung zu Ihnen und die Abholung zurück. Bis insgesamt 50 beladene Kilometer gilt eine Pauschale von 50 € netto (59,50 € inkl. 19 % MwSt.). Das entspricht beispielsweise 25 km Hinbringen plus 25 km Abholen. Jeder zusätzliche beladene Kilometer kostet 1,10 € netto zuzüglich 19 % MwSt. Leerfahrten werden nicht berechnet. Beispiel bei 35 km Entfernung: insgesamt 70 beladene Kilometer, also 50 € + 20 × 1,10 € = 72 € netto (85,68 € inkl. MwSt.)."],
  ["Kann ich den Wagen selbst abholen?", "Die Modelle S und M können Sie nach Absprache selbst abholen. Teilen Sie uns Ihren Wunsch bei der Anfrage mit."],
  ["Wann wird der Wagen geliefert und wieder abgeholt?", "Meist liefern wir den Wagen einen Tag vor Ihrem Anlass und bauen ihn am abgestimmten Platz auf. Meist einen Tag nach Ihrem Anlass bauen wir ihn ab und holen ihn ab. Die genauen Termine stimmen wir mit Ihnen ab. Nach der Rückkehr reinigen wir den Wagen und senden Ihnen die Schlussrechnung."],
  ["Welche Tage zählen als Miettage?", "Liefer- und Abholtag zählen nicht als Miettage. Geben Sie den gewünschten Liefertag und Ihren tatsächlichen Nutzungszeitraum getrennt an. Bei längerer Mietdauer erhalten Sie günstigere Konditionen im persönlichen Angebot."],
  ["Wie muss der Wagen zurückgegeben werden?", "Bitte geben Sie den Wagen besenrein zurück. Für die Endreinigung inklusive Desinfektion berechnen wir immer eine Pauschale von 50 € zusätzlich zur Miete – auch bei besenreiner Rückgabe. Bei außergewöhnlicher Verschmutzung können zusätzliche Reinigungskosten entstehen."],
  ["Gibt es eine Betreuung während der Veranstaltung?", "Eine Betreuung der Toilettenwagen durch einen Partner ist separat auf Anfrage möglich. Dies ist eine Betreuung der Sanitäranlagen, kein Security- oder Bewachungsdienst."],
  ["Kann ich für eine Firma oder eine Baustelle anfragen?", "Gewerbliche Anfragen sind willkommen: Wählen Sie im Formular Firma / gewerblich und geben Sie Ihre Rechnungsanschrift getrennt vom Aufstellort an. Baustellen bedienen wir nicht."],
  ["Darf die Rechnungsanschrift vom Aufstellort abweichen?", "Ja. Tragen Sie den Aufstellort und die Rechnungsanschrift getrennt ein. Nur wenn beide Adressen identisch sind, wählen Sie „Rechnungsanschrift entspricht dem Aufstellort“. Das gilt für private und gewerbliche Anfragen."],
  ["Warum sind Telefon und E-Mail beide erforderlich?", "Wir benötigen Ihre Telefonnummer für dringende Rückfragen und Ihre E-Mail-Adresse für Unterlagen und allgemeine Absprachen. Deshalb sind im Anfrageformular beide Angaben Pflichtfelder. Über die mitlaufende Kontaktleiste erreichen Sie jederzeit das Anfrageformular oder unseren WhatsApp-Chat."],
] as const;

export function Faq() {
  return <section id="faq" className={styles.faq} aria-labelledby="faq-title">
    <div className={styles.intro}><h2 id="faq-title">Gut zu wissen. Vor Ihrer Anfrage.</h2><p>Die wichtigsten Antworten zu Aufstellung, Ausstattung und Abrechnung.</p></div>
    <div>{questions.map(([question, answer]) => <details key={question} className={styles.item}><summary>{question}</summary><p>{answer}</p></details>)}</div>
  </section>;
}
