import styles from "./Faq.module.css";

const questions = [
  ["Welche TORK-Handtücher passen in welchen Wagen?", "Im Wagen S werden Tork Matic Advanced Handtuchrollen H1 verwendet. Für die Wagen M und L passen Tork Express Multifold Handtücher Universal H2. Bitte achten Sie beim Nachkauf auf das passende System. Diese Angaben beschreiben die passenden Handtücher, nicht den Umfang der Erstausstattung: S erhält Toilettenpapier; M und L erhalten Toilettenpapier, Seife und Tücher."],
  ["Welcher Wagen passt zu meiner Veranstaltung?", "Modell S ist für bis zu 200 Personen, M für bis zu 400 und L für bis zu 600 Personen vorgesehen. Im Anfrageformular wählen Sie das gewünschte Modell zuerst aus. Wenn Sie noch unsicher sind, wählen Sie „Noch unsicher“ – wir beraten Sie persönlich."],
  ["In welche Orte liefern Sie?", "Unser reguläres Einsatzgebiet reicht ungefähr 125 km um den Wagenstandort Niederdreisbach. Dazu gehören beispielsweise Daaden, Herdorf, Neunkirchen, Niederfischbach, Dillenburg, Haiger, Siegen, Netphen, Rennerod und Betzdorf. Weitere Strecken prüfen wir auf Anfrage."],
  ["Woran erkenne ich einen GEKA- oder Gardena-Anschluss?", "Eine GEKA-Kupplung erkennen Sie an zwei gegenüberliegenden Klauen und einem Dichtungsring. Bei Gardena hat das männliche Steckteil einen hervorstehenden Anschlusszapfen; das weibliche Schlauchstück besitzt eine Aufnahmeöffnung und eine Entriegelungshülse. Beispielabbildungen finden Sie weiter oben beim Wasseranschluss. Die genaue Ausführung stimmen wir vorab mit Ihnen ab."],
  ["Welche Anschlüsse und welchen Untergrund brauchen wir?", "Bitte stellen Sie 230 V Strom, einen Wasseranschluss mit GEKA- oder Gardena-Kupplung und einen geeigneten Abwasseranschluss bereit. Für den Abwasseranschluss empfehlen wir höchstens fünf Meter Abstand zum Wagen; die genaue Anschlussführung stimmen wir vor Ort ab. Die Aufstellfläche muss fest und eben sein. Wir bringen zehn Meter Frischwasserschlauch, Abwasserrohre und maßgefertigte Holzabdeckungen für Kanaldeckel mit."],
  ["Brauche ich eine Genehmigung für den Abwasseranschluss?", "Das hängt vom Aufstellort und vom vorgesehenen Anschluss ab. Bitte klären Sie vor der Veranstaltung mit dem örtlichen Kanalnetzbetreiber, ob der Anschluss für den Toilettenwagen genutzt werden darf und welche Zustimmung oder Genehmigung benötigt wird. Verwenden Sie keinen beliebigen Gully: Reine Regenwasserabläufe sind nicht für Toilettenabwasser geeignet. Den konkreten Anschluss und die Aufstellung stimmen wir vor Ort mit Ihnen ab."],
  ["Was ist als Erstausstattung enthalten?", "Modell S erhält Toilettenpapier. In M und L sind Toilettenpapier, Seife und Tücher als Erstausstattung vorhanden. Wenn die Erstausstattung aufgebraucht ist, können Sie Toilettenpapier, Seife und Papierhandtücher bei Herrmann & Smécz nachkaufen."],
  ["Wie werden Lieferung und Abholung berechnet?", "Wir addieren nur die Strecken mit angehängtem Toilettenwagen: die Lieferung zu Ihnen und die Abholung zurück. Bis insgesamt 50 beladene Kilometer gilt eine Pauschale von 50 € netto (59,50 € inkl. 19 % MwSt.). Das entspricht beispielsweise 25 km Hinbringen plus 25 km Abholen. Jeder zusätzliche beladene Kilometer kostet 1,10 € netto zuzüglich 19 % MwSt. Leerfahrten werden nicht berechnet. Beispiel bei 35 km Entfernung: insgesamt 70 beladene Kilometer, also 50 € + 20 × 1,10 € = 72 € netto (85,68 € inkl. MwSt.)."],
  ["Kann ich den Wagen selbst abholen?", "Die Modelle S und M können Sie nach Absprache selbst abholen. Teilen Sie uns Ihren Wunsch bei der Anfrage mit."],
  ["Wann wird der Wagen geliefert und wieder abgeholt?", "Meist liefern wir den Wagen einen Tag vor Ihrem Anlass und bauen ihn am abgestimmten Platz auf. Meist einen Tag nach Ihrem Anlass bauen wir ihn ab und holen ihn ab. Die genauen Termine stimmen wir mit Ihnen ab. Nach der Rückkehr reinigen wir den Wagen und senden Ihnen die Schlussrechnung."],
  ["Welche Tage zählen als Miettage?", "Liefer- und Abholtag zählen nicht als Miettage. Geben Sie den gewünschten Liefertag und Ihren tatsächlichen Nutzungszeitraum getrennt an. Bei längerer Mietdauer erhalten Sie günstigere Konditionen im persönlichen Angebot."],
  ["Wie muss der Wagen zurückgegeben werden?", "Bitte geben Sie den Wagen besenrein zurück. Die reguläre Endreinigung durch uns ist mit 50 € bereits im Preis enthalten und wird nicht zusätzlich berechnet. Bei außergewöhnlicher Verschmutzung können über die enthaltene Endreinigung hinaus Mehrkosten entstehen."],
  ["Gibt es eine Betreuung während der Veranstaltung?", "Eine Betreuung der Toilettenwagen durch einen Partner ist separat auf Anfrage möglich. Dies ist eine Betreuung der Sanitäranlagen, kein Security- oder Bewachungsdienst."],
  ["Kann ich für eine Firma oder eine Baustelle anfragen?", "Gewerbliche Anfragen sind willkommen: Wählen Sie im Formular Firma / gewerblich und geben Sie Ihre Rechnungsanschrift getrennt vom Aufstellort an. Baustellen bedienen wir nicht."],
  ["Darf die Rechnungsanschrift vom Aufstellort abweichen?", "Ja. Tragen Sie den Aufstellort und die Rechnungsanschrift getrennt ein. Nur wenn beide Adressen identisch sind, wählen Sie „Rechnungsanschrift entspricht dem Aufstellort“. Das gilt für private und gewerbliche Anfragen."],
  ["Warum sind Telefon und E-Mail beide erforderlich?", "Wir benötigen Ihre Telefonnummer für dringende Rückfragen und Ihre E-Mail-Adresse für Unterlagen und allgemeine Absprachen. Deshalb sind im Anfrageformular beide Angaben Pflichtfelder. Über die mitlaufende Kontaktleiste erreichen Sie jederzeit das Anfrageformular oder unseren WhatsApp-Chat."],
] as const;

export function Faq() {
  return <section id="faq" className={styles.faq} aria-labelledby="faq-title">
    <div className={styles.intro}><h2 id="faq-title">Gut zu wissen. Vor Ihrer Anfrage.</h2><p>Die wichtigsten Antworten zu Aufstellung, Ausstattung und Abrechnung.</p></div>
    <div>{questions.map(([question, answer]) => <details key={question} className={styles.item}><summary>{question}</summary><p>{answer}</p>{question === "Brauche ich eine Genehmigung für den Abwasseranschluss?" && <p>Örtliche Informationen: <a href="https://www.herdorf.de/ortsrecht/" target="_blank" rel="noopener noreferrer">Daaden-Herdorf</a> und <a href="https://esi-siegen.de/fragen-und-antworten/" target="_blank" rel="noopener noreferrer">Entsorgungsbetrieb Siegen</a>.</p>}</details>)}</div>
  </section>;
}
